apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: pcsmomo/posts
          # image: pcsmomo/posts:latest  # the same
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  # type: ClusterIP # if we don't specify it, it'd be ClusterIP as a default
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
