apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration # it should match with the label in template
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: pcsmomo/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: REDIS_HOST
              value: expiration-redis-srv
# we don't need a service as no service needs to access this expiration service
# expiration pod listens nats and handle it.